name: Deploy to S3 and CloudFront
on: 
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment with built-in caching
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Step 3: Create .env file for main application
      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL}}" >> .env
          cat .env

      # Step 4: Install dependencies and build the React app
      - run: npm ci
      - run: npm run build

      # Step 6: Sync the dist folder to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: acb-user
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-south-1
          SOURCE_DIR: dist

      # Step 7: Configure AWS CLI for CloudFront invalidation
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'ap-south-1'

      # Step 8: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
